// Canonical Center type lives in @/types (types/index.ts).
// This file only exports utility input types derived from it.
import type { Center } from "@/types";

export type { Center };
// centerCode is omitted from CreateCenterInput — it is auto-generated by the service
export type CreateCenterInput = Omit<Center, "id" | "centerCode" | "createdAt" | "updatedAt">;
export type UpdateCenterInput = Partial<Omit<Center, "id" | "createdAt">>;
